# Generated by Django 4.0.4 on 2022-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_coordinates', models.DecimalField(decimal_places=4, max_digits=20)),
                ('location_info', models.CharField(max_length=255)),
            ],
        ),
    ]
