# Generated by Django 4.0.4 on 2022-05-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_coordinates',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=45),
            preserve_default=False,
        ),
    ]
