# Generated by Django 4.0.4 on 2022-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_bio', models.CharField(max_length=255)),
                ('user_reputation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_verified', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('user_photo', models.ImageField(upload_to='')),
                ('user_theme', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
